#@TYPE: Machine
#@NAME: i.MX 93 EVK EasyEVSE
#@DESCRIPTION: i.MX 93 Evaluation Kit EasyEVSE configuration
#@MAINTAINER: Octavian-Tiberiu Sirbu <octavian-tiberiu.sirbu@nxp.com>

require conf/machine/imx93evk.conf

# Include device trees for other boards for internal test
KERNEL_DEVICETREE += " \
	freescale/imx93-11x11-evk-evse.dtb \
	freescale/imx93-11x11-evk-evse-lvds.dtb \
	freescale/imx93-11x11-evk-evse-ph1_2-cg5317.dtb \
"

KERNEL_DEVICETREE_BASENAME = "imx93-11x11-evk"

# Default version 1.4.0 from meta-everest fails to download
PREFERRED_VERSION_python3-poetry-core ?= "1.9.0"
# There is a mismatch between versions of python packages installed by
# poky/openembedded and versions selected by meta-everest. We force
# using the ones that do not have conflicts or build issues
PREFERRED_VERSION_python3-poetry-core-native ?= "1.9.0"
PREFERRED_VERSION_python3-packaging ?= "24.1"

PREFERRED_VERSION_curl ?= "8.9.1"
PREFERRED_VERSION_curl-native ?= "8.9.1"
PREFERRED_VERSION_catch2 ?= "3.%"

# This is required as meta-everest packages are not compatible with styhead
ERROR_QA:remove = " patch-status"
WARN_QA:append = " patch-status"

INSANE_SKIP:everest-framework += "already-stripped"
