# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nxp-everest-mpu"
BBFILE_PATTERN_meta-nxp-everest-mpu = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nxp-everest-mpu = "8"

LAYERDEPENDS_meta-nxp-everest-mpu = "fsl-bsp-release imx-demo meta-nxp-evse-common"
LAYERSERIES_COMPAT_meta-nxp-everest-mpu = "langdale mickledore"

SRC_BRANCH ?= "dev"
