active_modules:
  evse_manager_1:
    module: EvseManager
    mapping:
      module:
        evse: 1
    config_module:
      connector_id: 1
      connector_type: cType2
      evse_id: RO*NXP*E1234567*1
      ac_hlc_enabled: true
      ac_enforce_hlc: true
      ac_hlc_enabled: true
      contract_certificate_installation_enabled: false
      has_ventilation: false
      payment_enable_contract: false
      session_logging: true
      session_logging_path: /tmp/everest
      supported_iso_ac_bpt: true
      bpt_channel: Unified
      bpt_generator_mode: GridFollowing
      bpt_grid_code_island_method: Passive
    connections:
      bsp:
        - module_id: SigboardNXP0
          implementation_id: board_support
      ac_rcd:
        - module_id: SigboardNXP0
          implementation_id: rcd
      powermeter_grid_side:
        - module_id: SigboardNXP0
          implementation_id: powermeter
      powermeter_car_side:
        - module_id: SigboardNXP0
          implementation_id: powermeter
      slac:
        - module_id: EvseSlac0
          implementation_id: main
      hlc:
        - module_id: Evse15118D200
          implementation_id: charger
      store:
        - module_id: persistent_store
          implementation_id: main
  EvseSecurity0:
    module: EvseSecurity
    config_module:
      mf_ca_bundle: iso20/ca/mf/MF_CA_BUNDLE.pem
      mo_ca_bundle: iso20/ca/mo/MO_CA_BUNDLE.pem
      v2g_ca_bundle: iso20/ca/v2g/V2G_CA_BUNDLE.pem
      secc_leaf_cert_directory: iso20/client/cso
      secc_leaf_key_directory: iso20/client/cso
      private_key_password: "123456"
  EvseSlac0:
    module: EvseSlac
    config_implementation:
      main:
        device: eth0
        set_key_timeout_ms: 500
  Evse15118D200:
    module: Evse15118D20
    config_module:
      enforce_tls_1_3: true
      supported_scheduled_mode: true
      supported_dynamic_mode: false
      negative_bidirectional_limits: true
    connections:
      security:
        - module_id: EvseSecurity0
          implementation_id: main
      iso15118_vas: []
  SigboardNXP0:
    module: SigboardNXP
    config_module:
      serial_port: /dev/ttyLP2
      caps_min_current_A: 0
      caps_max_current_A: 32
  auth:
    module: Auth
    config_module:
      selection_algorithm: PlugEvents
      connection_timeout: 60
    connections:
      token_provider:
        - module_id: PN7160TokenProvider0
          implementation_id: main
      token_validator:
        - module_id: token_validator_dummy
          implementation_id: main
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
      kvs:
        - module_id: persistent_store
          implementation_id: main
  energy_manager:
    module: EnergyManager
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  grid_connection_point:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32
      phase_count: 1
    connections:
      energy_consumer:
        - module_id: evse_manager_1
          implementation_id: energy_grid
      powermeter:
        - module_id: SigboardNXP0
          implementation_id: powermeter
      price_information: []
  persistent_store:
    module: PersistentStore
  PN7160TokenProvider0:
    module: PN7160TokenProvider
  token_validator_dummy:
    module: DummyTokenValidator
    config_implementation:
      main:
        validation_result: Accepted
        validation_reason: Token valid
        sleep: 0.25
  error_history:
    module: ErrorHistory
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
  system:
    module: System
    connections:
      store:
        - module_id: persistent_store
          implementation_id: main
  evse_manager_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: evse_manager_consumer_API
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: evse_manager_1
  auth_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: auth_consumer_API
    connections:
      auth:
        - implementation_id: main
          module_id: auth
