active_modules:
  EvseManager0:
    config_module:
      ac_enforce_hlc: false
      ac_hlc_enabled: false
      ac_hlc_use_5percent: false
      ac_nominal_voltage: 230
      ac_with_soc: false
      autocharge_use_slac_instead_of_hlc: false
      cable_check_enable_imd_self_test: false
      cable_check_wait_below_60V_before_finish: true
      cable_check_wait_number_of_imd_measurements: 1
      central_contract_validation_allowed: false
      charge_mode: AC
      connector_id: 1
      connector_type: Unknown
      contract_certificate_installation_enabled: true
      dbg_hlc_auth_after_tstep: false
      dc_isolation_voltage_V: 0
      disable_authentication: false
      enable_autocharge: false
      ev_receipt_required: false
      evse_id: RO*NXP*E1234567*1
      evse_id_din: 49A80737A45678
      external_ready_to_start_charging: false
      fail_on_powermeter_errors: true
      hack_allow_bpt_with_iso2: false
      hack_fix_hlc_integer_current_requests: false
      hack_pause_imd_during_precharge: false
      hack_present_current_offset: 0
      hack_simplified_mode_limit_10A: false
      hack_skoda_enyaq: false
      has_ventilation: false
      initial_meter_value_timeout_ms: 5000
      inoperative_error_use_vendor_id: false
      lock_connector_in_state_b: true
      logfile_suffix: session_uuid
      payment_enable_contract: false
      payment_enable_eim: false
      raise_mrec9: false
      request_zero_power_in_idle: false
      sae_j2847_2_bpt_enabled: false
      sae_j2847_2_bpt_mode: V2G
      session_logging: true
      session_logging_path: /tmp/everest
      session_logging_xml: true
      soft_over_current_measurement_noise_A: 0.5
      soft_over_current_timeout_ms: 7000
      soft_over_current_tolerance_percent: 10
      state_F_after_fault_ms: 300
      switch_3ph1ph_cp_state: X1
      switch_3ph1ph_delay_s: 10
      uk_smartcharging_random_delay_at_any_change: false
      uk_smartcharging_random_delay_enable: false
      uk_smartcharging_random_delay_max_duration: 600
    connections:
      bsp:
        - implementation_id: board_support
          module_id: SigboardNXP0
    module: EvseManager
  PN7160TokenProvider0:
    config_implementation:
      main:
        debug: false
        disable_nfc_rfid: false
        token_debounce_interval_ms: 3000
    connections: {}
    module: PN7160TokenProvider
  SigboardNXP0:
    config_module:
      baud_rate: 115200
      meter_present: true
      caps_max_current_A: 32
      caps_min_current_A: 0
      debug: false
      serial_port: /dev/ttyLP2
    connections: {}
    module: SigboardNXP
  auth:
    config_module:
      connection_timeout: 60
      ignore_connector_faults: false
      master_pass_group_id: ''
      prioritize_authorization_over_stopping_transaction: true
      selection_algorithm: PlugEvents
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: EvseManager0
      token_provider:
        - implementation_id: main
          module_id: PN7160TokenProvider0
      token_validator:
        - implementation_id: main
          module_id: token_validator
    module: Auth
  energy_manager:
    config_module:
      debug: false
      nominal_ac_voltage: 230
      schedule_interval_duration: 60
      schedule_total_duration: 1
      slice_ampere: 0.5
      slice_watt: 500
      switch_3ph1ph_max_nr_of_switches_per_session: 0
      switch_3ph1ph_power_hysteresis_W: 200
      switch_3ph1ph_switch_limit_stickyness: DontChange
      switch_3ph1ph_time_hysteresis_s: 600
      switch_3ph1ph_while_charging_mode: Never
      update_interval: 1
    connections:
      energy_trunk:
        - implementation_id: energy_grid
          module_id: grid_connection_point
    module: EnergyManager
  grid_connection_point:
    config_module:
      fuse_limit_A: 32
      phase_count: 1
    connections:
      energy_consumer:
        - implementation_id: energy_grid
          module_id: EvseManager0
    module: EnergyNode
  token_validator:
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    connections: {}
    module: DummyTokenValidator
################################################################
  evse_manager_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: evse_manager_consumer_API
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: EvseManager0
  auth_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: auth_consumer_API
    connections:
      auth:
        - implementation_id: main
          module_id: auth