active_modules:
  EvseManager0:
    config_module:
      cable_check_enable_imd_self_test: false
      connector_id: 1
      connector_type: cType2
      evse_id: RO*NXP*E1234567*1
      has_ventilation: false
      payment_enable_contract: false
      session_logging: true
      session_logging_path: /tmp/everest
    connections:
      bsp:
        - implementation_id: board_support
          module_id: SigboardNXP0
    module: EvseManager
  PN7160TokenProvider0:
    module: PN7160TokenProvider
  SigboardNXP0:
    config_module:
      caps_max_current_A: 32
      caps_min_current_A: 0
      serial_port: /dev/ttyLP2
    module: SigboardNXP
  auth:
    config_module:
      connection_timeout: 60
      selection_algorithm: PlugEvents
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: EvseManager0
      token_provider:
        - implementation_id: main
          module_id: PN7160TokenProvider0
      token_validator:
        - implementation_id: main
          module_id: token_validator
    module: Auth
  energy_manager:
    connections:
      energy_trunk:
        - implementation_id: energy_grid
          module_id: grid_connection_point
    module: EnergyManager
  grid_connection_point:
    config_module:
      fuse_limit_A: 32
      phase_count: 1
    connections:
      energy_consumer:
        - implementation_id: energy_grid
          module_id: EvseManager0
    module: EnergyNode
  token_validator:
    config_implementation:
      main:
        sleep: 0.25
        validation_reason: Token seems valid
        validation_result: Accepted
    module: DummyTokenValidator
  evse_manager_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: evse_manager_consumer_API
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: EvseManager0
  auth_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: auth_consumer_API
    connections:
      auth:
        - implementation_id: main
          module_id: auth
