active_modules:
  evse_manager_1:
    module: EvseManager
    mapping:
      module:
        evse: 1
    config_module:
      connector_id: 1
      connector_type: cType2
      evse_id: RO*NXP*E1234567*1
      session_logging: true
      session_logging_xml: false
      session_logging_path: /tmp/everest
      cable_check_enable_imd_self_test: false
      has_ventilation: false
      payment_enable_contract: false
    connections:
      bsp:
        - implementation_id: board_support
          module_id: SigboardNXP0
      powermeter_grid_side:
        - module_id: SigboardNXP0
          implementation_id: powermeter
      powermeter_car_side:
        - implementation_id: powermeter
          module_id: SigboardNXP0
  SigboardNXP0:
    config_module:
      caps_max_current_A: 32
      caps_min_current_A: 0
      serial_port: /dev/ttyLP2
    module: SigboardNXP
  ocpp:
    module: OCPP201
    connections:
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
      auth:
        - module_id: auth_dummy
          implementation_id: main
      system:
        - module_id: system
          implementation_id: main
      security:
        - module_id: evse_security
          implementation_id: main
      evse_energy_sink:
        - module_id: grid_connection_point
          implementation_id: external_limits
        - module_id: evse_manager_1_ocpp_sink
          implementation_id: external_limits
      reservation:
        - module_id: auth_dummy
          implementation_id: reservation
    access:
      config:
        allow_global_read: true
        allow_global_write: false
        allow_set_read_only: false
        modules:
          auth:
            allow_read: true
            allow_write: true
            allow_set_read_only: true
  persistent_store:
    module: PersistentStore
  evse_security:
    module: EvseSecurity
    config_module:
      csms_ca_bundle: iso2/ca/csms/CSMS_CA_BUNDLE.pem
      csms_leaf_cert_directory: iso2/client/csms
      csms_leaf_key_directory: iso2/client/csms
      mf_ca_bundle: iso2/ca/mf/MF_CA_BUNDLE.pem
      mo_ca_bundle: iso2/ca/mo/MO_CA_BUNDLE.pem
      secc_leaf_cert_directory: iso2/client/cso
      secc_leaf_key_directory: iso2/client/cso
      v2g_ca_bundle: iso2/ca/v2g/V2G_CA_BUNDLE.pem
      private_key_password: '123456'
  token_provider_dummy:
    module: DummyTokenProvider
    config_implementation:
      main:
        timeout: 10
        token: 046A1A52645780
    connections:
      evse:
        - implementation_id: evse
          module_id: evse_manager_1
  auth_dummy:
    module: Auth
    config_module:
      connection_timeout: 60
      ignore_connector_faults: true
    connections:
      token_provider:
        - implementation_id: main
          module_id: token_provider_dummy
      token_validator:
        - implementation_id: main
          module_id: token_validator_dummy
      evse_manager:
        - implementation_id: evse
          module_id: evse_manager_1
      kvs:
        - module_id: persistent_store
          implementation_id: main
  token_validator_dummy:
    module: DummyTokenValidator
    config_implementation:
      main:
        sleep: .5
        validation_reason: Token seems DUMMY
        validation_result: Accepted
  energy_manager:
    module: EnergyManager
    config_module:
      slice_ampere: 1.0
      slice_watt: 1000
      schedule_total_duration: 5
    connections:
      energy_trunk:
        - module_id: grid_connection_point
          implementation_id: energy_grid
  evse_manager_1_ocpp_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32.0
      phase_count: 1
    connections:
      energy_consumer:
        - module_id: evse_manager_1
          implementation_id: energy_grid
  evse_manager_1_api_sink:
    module: EnergyNode
    mapping:
      module:
        evse: 1
    config_module:
      fuse_limit_A: 32.0
      phase_count: 1
    connections:
      energy_consumer:
        - module_id: evse_manager_1_ocpp_sink
          implementation_id: energy_grid
      powermeter:
        - module_id: SigboardNXP0
          implementation_id: powermeter
  grid_connection_point:
    module: EnergyNode
    mapping:
      module:
        evse: 0
    config_module:
      fuse_limit_A: 40.0
      phase_count: 1
    connections:
      price_information: []
      energy_consumer:
        - module_id: evse_manager_1_api_sink
          implementation_id: energy_grid
  api:
    module: API
    connections:
      evse_manager:
        - module_id: evse_manager_1
          implementation_id: evse
      ocpp:
        - module_id: ocpp
          implementation_id: ocpp_generic
      error_history:
        - module_id: error_history
          implementation_id: error_history
      evse_energy_sink:
        - module_id: evse_manager_1_api_sink
          implementation_id: external_limits
  error_history:
    module: ErrorHistory
    config_implementation:
      error_history:
        database_path: /tmp/error_history.db
  system:
    module: System
  evse_manager_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: evse_manager_consumer_API
    connections:
      evse_manager:
        - implementation_id: evse
          module_id: evse_manager_1
  auth_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: auth_consumer_API
    connections:
      auth:
        - implementation_id: main
          module_id: auth_dummy
  ocpp_api:
    config_module:
      cfg_communication_check_to_s: 0
      cfg_heartbeat_interval_ms: 40000
    module: ocpp_consumer_API
    connections:
      ocpp:
        - implementation_id: ocpp_generic
          module_id: ocpp
      data_transfer:
        - module_id: ocpp
          implementation_id: data_transfer